- name: functions 
  hosts: local
  connection: local
  tasks:
  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 5 hrs
        trainer: kumar
    ansible.builtin.debug:
      msg: "Course information: {{ course | dict2items }}"

