- name: install packages
  hosts: webapp
  become: true
  tasks:
  - name: Install the packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - zip
    - tomcat