# - name: shell vs command
#   hosts: webapp
#   tasks:
#   - name: redirect ls command out to a file
#     ansible.builtin.command: "ls -l > /tmp/output.txt"

- name: shell vs command
  hosts: webapp
  tasks:
  - name: redirect ls command out to a file
    ansible.builtin.shell: "ls -l > /tmp/output.txt"
    register: command_result
  - name: print the outcome
    ansible.builtin.debug:
      msg: "{{ command_result }}"
    
